#!/usr/bin/env bash
set -euo pipefail

# === CONFIG ===
BASE="/Users/m2ultra/NOIZYLAB/Clients"
TEMPLATE_DIR="$BASE/_TEMPLATES"

if [ ! -d "$TEMPLATE_DIR" ]; then
  echo "ERROR: Template dir not found at: $TEMPLATE_DIR"
  echo "Make sure it exists and has 00-INTAKE, 10-REPORT, 20-ASSETS, 90-INVOICE."
  exit 1
fi

if [ $# -lt 1 ]; then
  echo "Usage: $(basename "$0") \"Client Name\""
  exit 1
fi

CLIENT_NAME="$1"
# spaces -> dashes for folder safety
SAFE_NAME=$(echo "$CLIENT_NAME" | tr ' ' '-' )

CLIENT_DIR="$BASE/$SAFE_NAME"

if [ -d "$CLIENT_DIR" ]; then
  echo "ERROR: Client folder already exists: $CLIENT_DIR"
  exit 1
fi

echo "Creating NoizyLab client folder for: $CLIENT_NAME"
echo "→ $CLIENT_DIR"

mkdir -p "$CLIENT_DIR"

# Copy template structure into client folder
cp -R "$TEMPLATE_DIR"/. "$CLIENT_DIR"/

DATE_STR=$(date +%Y-%m-%d)

# Pre-fill Intake + Report with basic header
INTAKE_FILE="$CLIENT_DIR/00-INTAKE/Intake.md"
REPORT_FILE="$CLIENT_DIR/10-REPORT/Report.md"

if [ -f "$INTAKE_FILE" ]; then
  cat <<EOF | cat - "$INTAKE_FILE" > "${INTAKE_FILE}.tmp" && mv "${INTAKE_FILE}.tmp" "$INTAKE_FILE"
<!-- Auto-generated by NoizyLab client script -->
# NoizyLab – Client Intake

- Client: $CLIENT_NAME
- Date: $DATE_STR

EOF
fi

if [ -f "$REPORT_FILE" ]; then
  cat <<EOF | cat - "$REPORT_FILE" > "${REPORT_FILE}.tmp" && mv "${REPORT_FILE}.tmp" "$REPORT_FILE"
<!-- Auto-generated by NoizyLab client script -->
# NoizyLab – Service Report

- Client: $CLIENT_NAME
- Date: $DATE_STR

EOF
fi

echo "Done. Client workspace ready."
echo "Intake:  $INTAKE_FILE"
echo "Report:  $REPORT_FILE"

