#!/bin/bash

# MC96Universe DEPLOY PERSISTENCE
# "Immutable" Module: Installing optimizations into the boot sequence.
# Purpose: Ensure SPEED survives a reboot.

LABEL="com.mc96universe.turboboost"
PLIST_PATH="/Library/LaunchDaemons/$LABEL.plist"

echo ">>> MC96Universe PERSISTENCE LAYER Initializing..."

# 1. Create the Master Optimization Script in a permanent location
INSTALL_DIR="/usr/local/bin"
SCRIPT_NAME="mc96_optimized_boot.sh"
SCRIPT_PATH="$INSTALL_DIR/$SCRIPT_NAME"

echo ">>> Creating Master Boot Script at $SCRIPT_PATH..."

# Write the script that runs continuously/at-boot
cat <<EOF > /tmp/$SCRIPT_NAME
#!/bin/bash
# MC96Universe Boot Sequencer
# Generated by deploy_persistence.sh

# 1. Sysctl Tuning (Turbo Boost v3)
sysctl -w net.inet.tcp.win_scale_factor=8
sysctl -w net.inet.tcp.sendspace=2097152
sysctl -w net.inet.tcp.recvspace=2097152
sysctl -w kern.ipc.maxsockbuf=16777216
sysctl -w net.inet.tcp.delayed_ack=0
sysctl -w net.inet.tcp.tso=0
sysctl -w net.inet.tcp.lro=0
sysctl -w kern.ipc.somaxconn=2048
sysctl -w net.inet.tcp.blackhole=2
sysctl -w net.inet.udp.blackhole=1
sysctl -w net.inet.tcp.path_mtu_discovery=0
sysctl -w net.inet.ip.fastforwarding=1

# 2. MTU Enforcement
# Find the gateway interface and set 9000
GATEWAY_IFACE=\$(netstat -rn | grep default | grep en | head -1 | awk '{print \$4}')
if [ ! -z "\$GATEWAY_IFACE" ]; then
    networksetup -setMTU "\$GATEWAY_IFACE" 9000
fi

EOF

# Move and chmod
sudo mv /tmp/$SCRIPT_NAME $SCRIPT_PATH
sudo chmod +x $SCRIPT_PATH

# 2. Create the LaunchDaemon plist
echo ">>> Creating LaunchDaemon at $PLIST_PATH..."

cat <<EOF > /tmp/$LABEL.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$SCRIPT_PATH</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
</dict>
</plist>
EOF

# Install plist
sudo mv /tmp/$LABEL.plist $PLIST_PATH
sudo chown root:wheel $PLIST_PATH
sudo chmod 644 $PLIST_PATH

# 3. Load
echo ">>> Loading Daemon..."
sudo launchctl load $PLIST_PATH

echo ">>> PERSISTENCE INSTALLED."
echo ">>> The MC96Universe will now auto-optimize on every boot."
