
import os
import shutil
import datetime

class SonicTemplator:
    """
    SONIC-TEMPLATOR: The Ultimate Audio Project Generator.
    Creates standardized folder structures for music production.
    """
    
    TEMPLATES = {
        "ableton": [
            "Project Info", "Samples/Recorded", "Samples/Imported", 
            "Samples/Processed", "Exports/Stems", "Exports/Master"
        ],
        "pro_tools": [
            "Audio Files", "Bounced Files", "Clip Groups", 
            "Session File Backups", "Video Files"
        ],
        "sample_pack": [
            "One Shots/Kicks", "One Shots/Snares", "One Shots/Hats", 
            "Loops/Drums", "Loops/Melodic", "Loops/Bass", "FX"
        ],
        "album": [
            "01_Demos", "02_Production", "03_Mixing", 
            "04_Mastering", "05_Artwork", "06_Release"
        ]
    }

    def __init__(self, root_path=None):
        # Default to Desktop if not specified, or configure via mc96_config
        self.root_path = root_path or os.path.expanduser("~/Desktop/NOIZY_PROJECTS")

    def create_project(self, name, template_type="ableton"):
        """Creates a new project directory structure."""
        if template_type not in self.TEMPLATES:
            return {"error": f"Unknown template: {template_type}"}
            
        timestamp = datetime.datetime.now().strftime("%Y%m%d")
        base_dir = os.path.join(self.root_path, f"{timestamp}_{name}")
        
        try:
            if not os.path.exists(base_dir):
                os.makedirs(base_dir)
                
            structure = self.TEMPLATES[template_type]
            for folder in structure:
                os.makedirs(os.path.join(base_dir, folder), exist_ok=True)
                
            # Create a README or Project Info file
            with open(os.path.join(base_dir, "PROJECT_INFO.md"), 'w') as f:
                f.write(f"# {name}\n")
                f.write(f"Type: {template_type.upper()}\n")
                f.write(f"Created: {datetime.datetime.now()}\n")
                f.write("Generated by SONIC-TEMPLATOR (MC96 GABRIEL)\n")
                
            return {
                "status": "success", 
                "path": base_dir,
                "template": template_type
            }
        except Exception as e:
            return {"error": str(e)}

if __name__ == "__main__":
    t = SonicTemplator()
    print(t.create_project("New_Hit_Song", "ableton"))
