// scripts/setup-wizard.js
// Interactive Setup Wizard

import { createInterface } from "readline";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { execSync } from "child_process";

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (prompt) => {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
};

console.log(`
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║       NOIZYLAB DNS & Email Configuration Wizard          ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝

This wizard will help you configure your DNS and email settings.
`);

async function run() {
  const config = {};

  // Check if .env exists
  const envExists = existsSync("./.env");
  if (envExists) {
    console.log("⚠️  Warning: .env file already exists.");
    const overwrite = await question("Do you want to overwrite it? (yes/no): ");
    if (overwrite.toLowerCase() !== "yes" && overwrite.toLowerCase() !== "y") {
      console.log("\nSetup cancelled. Your existing .env file was not modified.\n");
      rl.close();
      return;
    }
  }

  console.log("\n--- GoDaddy API Credentials ---");
  console.log("Get your API credentials from: https://developer.godaddy.com/keys\n");

  config.GODADDY_API_KEY = await question("GoDaddy API Key: ");
  config.GODADDY_API_SECRET = await question("GoDaddy API Secret: ");

  console.log("\n--- Domain Configuration ---");
  const domainDefault = "noizylab.ca";
  const domain = await question(`Domain (default: ${domainDefault}): `);
  config.DOMAIN = domain || domainDefault;

  console.log("\n--- Mail Server Configuration ---");
  console.log("Enter your mail server's IP address.");
  console.log("If you don't have one yet, you can update this later.\n");

  config.MAIL_SERVER_IP = await question("Mail Server IP: ");

  console.log("\n--- DKIM Configuration ---");
  const generateDKIM = await question(
    "Do you want to generate DKIM keys now? (yes/no): "
  );

  if (
    generateDKIM.toLowerCase() === "yes" ||
    generateDKIM.toLowerCase() === "y"
  ) {
    const selector = await question("DKIM Selector (default: selector1): ");
    config.DKIM_SELECTOR = selector || "selector1";

    // Will be generated by the DKIM script
    config.DKIM_PUBLIC_KEY = "WILL_BE_GENERATED";
    config.DKIM_PRIVATE_KEY = "WILL_BE_GENERATED";
  } else {
    config.DKIM_SELECTOR = "selector1";
    config.DKIM_PUBLIC_KEY = "your_public_key_here";
    config.DKIM_PRIVATE_KEY = "your_private_key_here";
  }

  console.log("\n--- Email Test Configuration (Optional) ---");
  const configureEmail = await question(
    "Do you want to configure email testing? (yes/no): "
  );

  if (
    configureEmail.toLowerCase() === "yes" ||
    configureEmail.toLowerCase() === "y"
  ) {
    config.SMTP_HOST = await question("SMTP Host: ");
    config.SMTP_PORT = await question("SMTP Port (default: 587): ") || "587";
    config.SMTP_USER = await question("SMTP Username: ");
    config.SMTP_PASS = await question("SMTP Password: ");
    config.TEST_EMAIL_TO = await question("Test Email Recipient: ");
  } else {
    config.SMTP_HOST = "smtp.example.com";
    config.SMTP_PORT = "587";
    config.SMTP_USER = "your_email@noizylab.ca";
    config.SMTP_PASS = "your_smtp_password";
    config.TEST_EMAIL_TO = "test@example.com";
  }

  // Generate .env content
  const envContent = `# GoDaddy API Credentials
# Get these from: https://developer.godaddy.com/keys
GODADDY_API_KEY=${config.GODADDY_API_KEY}
GODADDY_API_SECRET=${config.GODADDY_API_SECRET}

# Domain Configuration
DOMAIN=${config.DOMAIN}

# Mail Server Configuration
MAIL_SERVER_IP=${config.MAIL_SERVER_IP}

# DKIM Configuration
# Generate DKIM keys with: npm run generate:dkim
DKIM_SELECTOR=${config.DKIM_SELECTOR}
DKIM_PUBLIC_KEY=${config.DKIM_PUBLIC_KEY}
DKIM_PRIVATE_KEY=${config.DKIM_PRIVATE_KEY}

# Email Test Configuration (optional)
SMTP_HOST=${config.SMTP_HOST}
SMTP_PORT=${config.SMTP_PORT}
SMTP_USER=${config.SMTP_USER}
SMTP_PASS=${config.SMTP_PASS}
TEST_EMAIL_TO=${config.TEST_EMAIL_TO}
`;

  // Save .env file
  writeFileSync("./.env", envContent);
  console.log("\n✅ Configuration saved to .env\n");

  // Generate DKIM if requested
  if (
    generateDKIM.toLowerCase() === "yes" ||
    generateDKIM.toLowerCase() === "y"
  ) {
    console.log("Generating DKIM keys...\n");
    try {
      execSync("node scripts/generate-dkim.js", { stdio: "inherit" });
    } catch (error) {
      console.error("❌ Error generating DKIM keys:", error.message);
    }
  }

  console.log("\n=== Setup Complete! ===\n");
  console.log("Next steps:\n");

  if (
    generateDKIM.toLowerCase() !== "yes" &&
    generateDKIM.toLowerCase() !== "y"
  ) {
    console.log("1. Generate DKIM keys:");
    console.log("   npm run generate:dkim\n");
  }

  console.log("2. Setup DNS records:");
  console.log("   npm run dns:setup\n");

  console.log("3. Verify configuration:");
  console.log("   npm run dns:verify\n");

  console.log("4. Test email sending:");
  console.log("   npm run test:email\n");

  console.log("For help, run: npm start\n");

  rl.close();
}

run().catch((error) => {
  console.error("\n❌ Setup error:", error.message);
  rl.close();
  process.exit(1);
});
