#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

ChapterWithContentResponseModelState = typing.Union[typing.Literal["default", "converting"], typing.Any]
