#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

DependentAvailableAgentIdentifierAccessLevel = typing.Union[
    typing.Literal["admin", "editor", "commenter", "viewer"], typing.Any
]
