#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

EmbedVariant = typing.Union[typing.Literal["tiny", "compact", "full", "expandable"], typing.Any]
