#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

ChapterContentBlockInputModelSubType = typing.Union[typing.Literal["p", "h1", "h2", "h3"], typing.Any]
