#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalization = typing.Union[
    typing.Literal["auto", "on", "off"], typing.Any
]
