#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

CaptionStyleVerticalPlacementModelAlign = typing.Union[typing.Literal["top", "center", "bottom"], typing.Any]
