#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

ConversationHistoryTranscriptCommonModelOutputSourceMedium = typing.Union[typing.Literal["audio", "text"], typing.Any]
