#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

BodyCreatePodcastV1StudioPodcastsPostQualityPreset = typing.Union[
    typing.Literal["standard", "high", "highest", "ultra", "ultra_lossless"], typing.Any
]
