#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

DubbingListRequestFilterByCreator = typing.Union[typing.Literal["personal", "others", "all"], typing.Any]
