#!/usr/bin/env python3
# This file was auto-generated by Fern from our API Definition.

import typing

CaptionStyleWordAnimationModelEnterType = typing.Union[typing.Literal["none", "fade", "scale"], typing.Any]
