import os
import wave
import aifc
import json

ROOT_DIR = "/Volumes/6TB/Sample_Libraries"
REPORT_FILE = "/Users/m2ultra/.gemini/robs_originals_report.md"

originals = []
commercial = []
errors = []

print(f"🕵️‍♀️ CB_01 AUDIO DETECTIVE STARTING...")
print(f"Target: Detect 24-bit (ROB) vs 16-bit (Commercial) in {ROOT_DIR}")

def get_bit_depth(file_path):
    ext = os.path.splitext(file_path)[1].lower()
    try:
        if ext == '.wav':
            with wave.open(file_path, 'rb') as f:
                return f.getsampwidth() * 8
        elif ext == '.aif' or ext == '.aiff':
            with aifc.open(file_path, 'rb') as f:
                return f.getsampwidth() * 8
    except Exception as e:
        return None
    return None

for root, dirs, files in os.walk(ROOT_DIR):
    for file in files:
        ext = os.path.splitext(file)[1].lower()
        if ext in ['.wav', '.aif', '.aiff']:
            path = os.path.join(root, file)
            depth = get_bit_depth(path)
            
            if depth == 24:
                originals.append(path)
            elif depth == 16:
                commercial.append(path)
            elif depth:
                 # Other bit depths (8, 32, etc)
                 pass
            else:
                errors.append(path)

print(f"\n✅ ANALYSIS COMPLETE")
print(f"Found {len(originals)} potential ORIGINAL ROB RECORDINGS (24-bit)")
print(f"Found {len(commercial)} COMMERCIAL SAMPLES (16-bit)")

# Generate Report
report = f"""# 🎵 ROB'S ORIGINAL WORKS REPORT
**Generated by:** CB_01
**Source:** `{ROOT_DIR}`

## 💎 POTENTIAL ORIGINALS (24-Bit Audio)
**Count:** {len(originals)}

"""

if originals:
    # List first 50 to avoid huge file
    for path in originals[:50]:
        report += f"- `{os.path.basename(path)}`\n  - Path: {path}\n"
    
    if len(originals) > 50:
        report += f"\n...and {len(originals) - 50} more."
else:
    report += "No 24-bit files found in this directory."

with open(REPORT_FILE, "w") as f:
    f.write(report)

print(f"📄 Report saved to {REPORT_FILE}")
