#!/usr/bin/env python3
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Paths
NOIZYLAB_ROOT = "/Users/m2ultra/NOIZYLAB"
GABRIEL_ROOT = os.path.join(NOIZYLAB_ROOT, "GABRIEL")
REPORTS_DIR = os.path.join(NOIZYLAB_ROOT, "reports")
INTEL_ENGINE = os.path.join(GABRIEL_ROOT, "intelligence_engine.py")
INTEL_REPORT_JSON = os.path.join(GABRIEL_ROOT, "intelligence_report.json")

def run_intel_engine():
    """Runs the intelligence engine to generate the latest JSON report."""
    print("🔍 Running Intelligence Engine...")
    import subprocess
    try:
        subprocess.run([sys.executable, INTEL_ENGINE, GABRIEL_ROOT], check=True, capture_output=True)
        print("✅ Intelligence report JSON updated.")
    except Exception as e:
        print(f"❌ Error running intelligence engine: {e}")
        return False
    return True

def generate_markdown_report(json_data):
    """Converts JSON report data into a beautiful Markdown report."""
    timestamp = json_data.get("timestamp", datetime.now().isoformat())
    date_str = datetime.fromisoformat(timestamp).strftime("%Y-%m-%d %H:%M:%S")
    stats = json_data.get("stats", {})
    insights = json_data.get("insights", [])

    md = f"# 🧠 NOIZY.ai Daily Intelligence Report\n"
    md += f"**Timestamp:** `{date_str}`\n\n"
    
    md += "## 📊 Codebase Statistics\n\n"
    md += f"- **Total Files:** `{stats.get('total_files', 0):,}`\n"
    md += f"- **Total Lines:** `{stats.get('total_lines', 0):,}`\n"
    md += f"- **Complexity Score:** `{stats.get('complexity_score', 0):,}`\n"
    md += f"- **Scan Time:** `{stats.get('scan_time', 0)}s`\n\n"

    md += "### 🌐 Language Distribution\n\n"
    md += "| Language | Files | Lines | Size |\n"
    md += "| :--- | :--- | :--- | :--- |\n"
    langs = stats.get("languages", {})
    for lang, data in sorted(langs.items(), key=lambda x: x[1]['lines'], reverse=True):
        md += f"| {lang} | {data['files']:,} | {data['lines']:,} | {data['bytes'] / 1024 / 1024:.2f} MB |\n"
    md += "\n"

    md += "## 💡 Key Insights\n\n"
    if insights:
        for insight in insights:
            icon = "⚠️" if insight["type"] == "warning" else "ℹ️"
            md += f"### {icon} {insight['message']}\n"
            md += f"**Suggestion:** {insight['suggestion']}\n\n"
    else:
        md += "*No significant insights detected today.*\n\n"

    md += "## 🔥 Hot Files (Top 10 Complexity)\n\n"
    md += "| File Path | Complexity | Lines |\n"
    md += "| :--- | :---: | :---: |\n"
    hot_files = stats.get("hot_files", [])[:10]
    for f in hot_files:
        md += f"| `{f['file']}` | `{f['complexity']:,}` | `{f['lines']:,}` |\n"
    md += "\n---\n"
    md += "Generated by NOIZY.ai Intelligence Engine\n"
    
    return md

def main():
    if not run_intel_engine():
        sys.exit(1)

    if not os.path.exists(INTEL_REPORT_JSON):
        print(f"❌ Could not find report at {INTEL_REPORT_JSON}")
        sys.exit(1)

    with open(INTEL_REPORT_JSON, 'r') as f:
        data = json.load(f)

    report_md = generate_markdown_report(data)
    
    today = datetime.now().strftime("%Y-%m-%d")
    report_filename = f"DAILY_INTEL_{today}.md"
    report_path = os.path.join(REPORTS_DIR, report_filename)

    with open(report_path, 'w') as f:
        f.write(report_md)

    print(f"🚀 Daily Intelligence Report generated: {report_path}")
    return report_path

if __name__ == "__main__":
    main()
