
import os
import shutil
import datetime

class SonicTemplator:
    """
    SONIC-TEMPLATOR: The Ultimate Audio Project Generator.
    Creates standardized folder structures for music production.
    """
    
    TEMPLATES = {
        "ableton": [
            "Project Info", "Samples/Recorded", "Samples/Imported", 
            "Samples/Processed", "Exports/Stems", "Exports/Master",
            "Presets", "Config"
        ],
        "pro_tools": [
            "Audio Files", "Bounced Files", "Clip Groups", 
            "Session File Backups", "Video Files"
        ],
        "sample_pack": [
            "One Shots/Kicks", "One Shots/Snares", "One Shots/Hats", 
            "Loops/Drums", "Loops/Melodic", "Loops/Bass", "FX"
        ],
        "album": [
            "01_Demos", "02_Production", "03_Mixing", 
            "04_Mastering", "05_Artwork", "06_Release"
        ],
        "code": [
            "src", "tests", "docs", "scripts", "config", "data"
        ],
        "python": [
            "src", "tests", "docs", "venv"
        ]
    }

    def __init__(self, root_path=None):
        # Default to Desktop if not specified, or configure via mc96_config
        self.root_path = root_path or os.path.expanduser("~/Desktop/NOIZY_PROJECTS")

    def create_project(self, name, template_type="ableton"):
        """Creates a new project directory structure with smart files."""
        if template_type not in self.TEMPLATES:
            # Fallback to basic if unknown
            self.TEMPLATES[template_type] = ["General"]
            
        timestamp = datetime.datetime.now().strftime("%Y%m%d")
        base_dir = os.path.join(self.root_path, f"{timestamp}_{name}")
        
        try:
            if not os.path.exists(base_dir):
                os.makedirs(base_dir)
                
            structure = self.TEMPLATES[template_type]
            for folder in structure:
                os.makedirs(os.path.join(base_dir, folder), exist_ok=True)
                
            # Smart File Generation
            self._generate_readme(base_dir, name, template_type)
            self._generate_manifest(base_dir, name, template_type)
            
            if template_type in ["code", "python"]:
                self._generate_code_files(base_dir, name)
                
            return {
                "status": "success", 
                "path": base_dir,
                "template": template_type
            }
        except Exception as e:
            return {"error": str(e)}

    def _generate_readme(self, base_dir, name, type_):
        content = f"# {name}\n\nType: {type_.upper()}\nCreated: {datetime.datetime.now()}\n\n## Overview\nProject initialized by SONIC-TEMPLATOR (GABRIEL OMEGA).\n\n## Status\n[x] Structured\n[ ] In Progress\n"
        with open(os.path.join(base_dir, "README.md"), 'w') as f:
            f.write(content)

    def _generate_manifest(self, base_dir, name, type_):
        import json
        manifest = {
            "project_name": name,
            "template": type_,
            "created_at": datetime.datetime.now().isoformat(),
            "gabriel_version": "OMEGA-1.0",
            "tags": ["generated", type_]
        }
        with open(os.path.join(base_dir, "manifest.json"), 'w') as f:
            json.dump(manifest, f, indent=4)

    def _generate_code_files(self, base_dir, name):
        # .gitignore
        with open(os.path.join(base_dir, ".gitignore"), 'w') as f:
            f.write("__pycache__/\n*.pyc\nvenv/\n.DS_Store\n")
            
        # requirements.txt
        with open(os.path.join(base_dir, "requirements.txt"), 'w') as f:
            f.write("# GABRIEL PROJECT DEPENDENCIES\nrequests\n")

        # main.py defaults logic moved to Genesis, but blank here fits too
        if not os.path.exists(os.path.join(base_dir, "main.py")):
             with open(os.path.join(base_dir, "main.py"), 'w') as f:
                  f.write(f'"""\n{name} - Generated by Gabriel\n"""\n\ndef main():\n    print("System Online")\n\nif __name__ == "__main__":\n    main()')

if __name__ == "__main__":
    t = SonicTemplator()
    print(t.create_project("New_Hit_Song", "ableton"))
