#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                    CODE FORGE v1.0                                           ║
║                    AI-POWERED CODE GENERATION                                ║
║                                                                              ║
║  Generate complete code files with AI. Templates + Intelligence.            ║
║  Python, JavaScript, TypeScript, Shell, and more. GORUNFREE.                ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import os
import re
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class CodeTemplate:
    """Code generation template"""
    name: str
    language: str
    template: str
    description: str = ""


# Built-in templates
TEMPLATES = {
    "python_module": CodeTemplate(
        name="python_module",
        language="python",
        description="Python module with docstring and exports",
        template='''#!/usr/bin/env python3
"""
{module_name} - {description}
Generated by CODE FORGE | GORUNFREE x1000
"""

from typing import Optional, Any
from dataclasses import dataclass


@dataclass
class {class_name}:
    """
    {class_description}
    """
    {fields}
    
    def __post_init__(self):
        pass


def main():
    """Main entry point"""
    print("{module_name} initialized")


__all__ = ['{class_name}']


if __name__ == "__main__":
    main()
'''
    ),
    
    "python_cli": CodeTemplate(
        name="python_cli",
        language="python",
        description="Python CLI with argparse",
        template='''#!/usr/bin/env python3
"""
{name} - {description}
Generated by CODE FORGE | GORUNFREE x1000
"""

import argparse
import sys


def main():
    parser = argparse.ArgumentParser(description="{description}")
    parser.add_argument("command", help="Command to run")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    
    args = parser.parse_args()
    
    if args.verbose:
        print(f"Running: {{args.command}}")
    
    # TODO: Implement commands
    print(f"Command: {{args.command}}")


if __name__ == "__main__":
    main()
'''
    ),
    
    "python_api": CodeTemplate(
        name="python_api",
        language="python",
        description="FastAPI endpoint",
        template='''#!/usr/bin/env python3
"""
{name} API - {description}
Generated by CODE FORGE | GORUNFREE x1000
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional


app = FastAPI(title="{name}", description="{description}")


class {model_name}(BaseModel):
    {fields}


@app.get("/")
async def root():
    return {{"service": "{name}", "status": "online"}}


@app.get("/health")
async def health():
    return {{"status": "healthy"}}


@app.post("/{endpoint}")
async def create(item: {model_name}):
    return {{"created": True, "item": item}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
    ),
    
    "typescript_module": CodeTemplate(
        name="typescript_module",
        language="typescript",
        description="TypeScript module with types",
        template='''/**
 * {name} - {description}
 * Generated by CODE FORGE | GORUNFREE x1000
 */

export interface {interface_name} {{
  {fields}
}}

export class {class_name} implements {interface_name} {{
  {class_fields}
  
  constructor({constructor_params}) {{
    {constructor_body}
  }}
  
  public async execute(): Promise<void> {{
    console.log("{name} executing...");
  }}
}}

export default {class_name};
'''
    ),
    
    "shell_script": CodeTemplate(
        name="shell_script",
        language="shell",
        description="Shell script with error handling",
        template='''#!/bin/bash
#
# {name} - {description}
# Generated by CODE FORGE | GORUNFREE x1000
#

set -euo pipefail

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

log() {{ echo -e "${{GREEN}}[INFO]${{NC}} $1"; }}
warn() {{ echo -e "${{YELLOW}}[WARN]${{NC}} $1"; }}
error() {{ echo -e "${{RED}}[ERROR]${{NC}} $1" >&2; exit 1; }}

main() {{
    log "Starting {name}..."
    
    # TODO: Main logic here
    
    log "Done!"
}}

main "$@"
'''
    ),
    
    "cloudflare_worker": CodeTemplate(
        name="cloudflare_worker",
        language="javascript",
        description="Cloudflare Worker",
        template='''/**
 * {name} - {description}
 * Generated by CODE FORGE | GORUNFREE x1000
 */

export default {{
  async fetch(request, env) {{
    const url = new URL(request.url);
    
    if (url.pathname === '/') {{
      return new Response(JSON.stringify({{
        service: "{name}",
        status: "online"
      }}), {{
        headers: {{ 'Content-Type': 'application/json' }}
      }});
    }}
    
    if (url.pathname === '/api/{endpoint}' && request.method === 'POST') {{
      const data = await request.json();
      // TODO: Process data
      return new Response(JSON.stringify({{ success: true, data }}), {{
        headers: {{ 'Content-Type': 'application/json' }}
      }});
    }}
    
    return new Response('Not Found', {{ status: 404 }});
  }}
}};
'''
    ),
}


class CodeForge:
    """
    AI-Powered Code Generator
    
    Generate complete code files from templates and AI.
    """
    
    def __init__(self):
        self.templates = TEMPLATES.copy()
    
    def add_template(self, template: CodeTemplate):
        """Add a custom template"""
        self.templates[template.name] = template
    
    def list_templates(self) -> list[str]:
        """List available templates"""
        return list(self.templates.keys())
    
    def generate(self, template_name: str, output_path: Optional[Path] = None, **kwargs) -> str:
        """Generate code from template"""
        if template_name not in self.templates:
            raise ValueError(f"Unknown template: {template_name}")
        
        template = self.templates[template_name]
        
        # Fill in template
        code = template.template
        for key, value in kwargs.items():
            code = code.replace(f"{{{key}}}", str(value))
        
        # Write to file if path provided
        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(code)
            print(f"✅ Generated: {output_path}")
        
        return code
    
    def generate_with_ai(self, prompt: str, language: str = "python", output_path: Optional[Path] = None) -> str:
        """Generate code using AI"""
        try:
            from .turbo_dispatcher import dispatch
            
            system = f"""You are a code generator. Generate clean, production-ready {language} code.
Include proper error handling, type hints (if applicable), and documentation.
Return ONLY the code, no explanations. Start with appropriate shebang/header."""
            
            result = dispatch("ask", prompt, "Claude")
            
            if "response" in result:
                code = result["response"]
                
                # Extract code block if present
                if "```" in code:
                    match = re.search(r'```(?:\w+)?\n(.*?)```', code, re.DOTALL)
                    if match:
                        code = match.group(1)
                
                # Write to file
                if output_path:
                    output_path = Path(output_path)
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    output_path.write_text(code)
                    print(f"✅ AI Generated: {output_path}")
                
                return code
            
            return f"# Error: {result.get('error', 'Unknown error')}"
            
        except Exception as e:
            return f"# Error: {e}"
    
    def scaffold_project(self, name: str, project_type: str = "python", base_path: Path = None) -> Path:
        """Scaffold a complete project structure"""
        base = Path(base_path) if base_path else Path.cwd() / name
        base.mkdir(parents=True, exist_ok=True)
        
        if project_type == "python":
            # Create Python project structure
            (base / "src").mkdir(exist_ok=True)
            (base / "tests").mkdir(exist_ok=True)
            
            # Main module
            self.generate("python_module", 
                         base / "src" / f"{name}.py",
                         module_name=name,
                         description=f"{name} module",
                         class_name=name.title().replace("_", ""),
                         class_description=f"Main {name} class",
                         fields="name: str = 'default'")
            
            # CLI
            self.generate("python_cli",
                         base / "cli.py",
                         name=name,
                         description=f"{name} CLI")
            
            # README
            (base / "README.md").write_text(f"# {name}\n\nGenerated by CODE FORGE | GORUNFREE x1000\n")
            
            # Requirements
            (base / "requirements.txt").write_text("# Add dependencies here\n")
            
        elif project_type == "worker":
            # Cloudflare Worker project
            (base / "src").mkdir(exist_ok=True)
            
            self.generate("cloudflare_worker",
                         base / "src" / "index.js",
                         name=name,
                         description=f"{name} worker",
                         endpoint=name.lower())
            
            (base / "wrangler.toml").write_text(f'''name = "{name}"
main = "src/index.js"
compatibility_date = "2024-01-01"
''')
        
        print(f"🏗️ Project scaffolded: {base}")
        return base


# Factory
def create_forge() -> CodeForge:
    """Create a CodeForge instance"""
    return CodeForge()


__all__ = ['CodeTemplate', 'CodeForge', 'create_forge', 'TEMPLATES']


if __name__ == "__main__":
    print("╔══════════════════════════════════════════════════════════════╗")
    print("║              CODE FORGE v1.0                                 ║")
    print("║              AI-POWERED CODE GENERATION                      ║")
    print("╚══════════════════════════════════════════════════════════════╝")
    print()
    
    forge = create_forge()
    
    print("📋 Available Templates:")
    for name in forge.list_templates():
        template = forge.templates[name]
        print(f"   • {name} [{template.language}] - {template.description}")
