#!/usr/bin/env python3
"""
AI Development Assistant - Code that writes code
Learns your patterns and generates what you need.
"""
import ast
import re
from pathlib import Path
from uap_core import uap, UapEvent

class AICodeGenerator:
    def __init__(self):
        self.patterns = {}
        self.templates = {
            'fastapi_endpoint': '''
@app.{method}("/{path}")
async def {function_name}():
    """Auto-generated endpoint"""
    return {{"message": "Generated by AI Assistant"}}
''',
            'uap_agent': '''
def {agent_name}_agent():
    """Auto-generated UAP agent"""
    # TODO: Add your logic here
    uap.publish(UapEvent(
        topic='{topic}',
        payload={{'status': 'active'}},
        source='{agent_name}'
    ))
''',
            'test_function': '''
def test_{function_name}():
    """Auto-generated test"""
    # TODO: Add test logic
    assert True, "Test needs implementation"
'''
        }
    
    def analyze_codebase(self, directory: Path):
        """Analyze existing code to learn patterns"""
        patterns = {'functions': [], 'classes': [], 'imports': []}
        
        for file in directory.glob("**/*.py"):
            try:
                with open(file, 'r') as f:
                    tree = ast.parse(f.read())
                
                for node in ast.walk(tree):
                    if isinstance(node, ast.FunctionDef):
                        patterns['functions'].append(node.name)
                    elif isinstance(node, ast.ClassDef):
                        patterns['classes'].append(node.name)
                    elif isinstance(node, ast.Import):
                        for alias in node.names:
                            patterns['imports'].append(alias.name)
            except:
                continue
        
        self.patterns = patterns
        return patterns
    
    def generate_code(self, template_type: str, **kwargs):
        """Generate code from template"""
        if template_type in self.templates:
            return self.templates[template_type].format(**kwargs)
        return f"# TODO: Generate {template_type}"
    
    def suggest_improvements(self, code: str):
        """Suggest code improvements"""
        suggestions = []
        
        # Simple analysis
        if 'import *' in code:
            suggestions.append("Consider avoiding wildcard imports")
        
        if len(code.split('\n')) > 100:
            suggestions.append("Consider breaking this into smaller functions")
        
        if 'TODO' in code:
            suggestions.append("Don't forget to implement TODOs!")
        
        return suggestions
    
    def auto_document(self, function_code: str):
        """Generate documentation for a function"""
        # Extract function name
        match = re.search(r'def (\w+)\(', function_code)
        if match:
            func_name = match.group(1)
            return f'"""\n{func_name.replace("_", " ").title()}\nAuto-generated documentation.\n"""'
        return '"""Auto-generated documentation."""'

# Initialize AI assistant
ai_assistant = AICodeGenerator()

def ai_assistant_agent():
    """Agent that monitors code and provides suggestions"""
    # Analyze current directory
    patterns = ai_assistant.analyze_codebase(Path('.'))
    
    uap.publish(UapEvent(
        topic='code_analysis',
        payload=patterns,
        source='ai_assistant'
    ))

# Register the AI assistant agent
uap.register_agent('ai_assistant', ai_assistant_agent)

if __name__ == "__main__":
    print("🤖 AI Development Assistant - Code that writes code!")