import argparse
import hashlib
import random
import time


def generate_sovereign_key(tremor_sample, heartbeat_bpm):
    """
    Creates a 256-bit key that can ONLY be generated by YOUR nervous system.
    """
    # Combine the frequency spectrum of your hand with your heart rate
    raw_bio_signature = f"{tremor_sample}-{heartbeat_bpm}-GENESIS_198x"

    # Secure Hash (SHA-256)
    sovereign_key = hashlib.sha256(raw_bio_signature.encode()).hexdigest()

    print(f"🔒 AURA_KEY_GENERATED: {sovereign_key[:8]}...[LOCKED]")
    return sovereign_key


def simulate_tremor_sample():
    # Placeholder: in production, ingest P24 spectral data
    return round(random.uniform(2.5, 4.0), 4)


def zen_lock_loop():
    print("🥁 OSCILLATOR: Waiting for P24 Seismic Sync...")
    time.sleep(1)
    tremor = simulate_tremor_sample()
    heartbeat_bpm = random.randint(58, 72)
    print(f"🥁 OSCILLATOR: Bio rhythm captured (tremor={tremor}Hz, bpm={heartbeat_bpm})")
    generate_sovereign_key(tremor, heartbeat_bpm)
    print("✅ AURA_LOCKED: Pulse matched to Genesis Baseline.")


def main():
    parser = argparse.ArgumentParser(description="Aura oscillator / bio-key generator")
    parser.add_argument("--mode", default="ZEN_LOCK", help="Mode: ZEN_LOCK")
    parser.add_argument("--ignite-key", action="store_true", help="Generate key once and exit.")
    args = parser.parse_args()

    if args.ignite_key:
        zen_lock_loop()
        return

    if args.mode.upper() == "ZEN_LOCK":
        zen_lock_loop()
    else:
        print(f"Unknown mode {args.mode}; defaulting to ZEN_LOCK")
        zen_lock_loop()


if __name__ == "__main__":
    main()
